version: "3.3"

services:
    apiserver:
        build: ./docker/apiserver
        ports:
            - "8000:8000"
        volumes:
            - ./src:/usr/src/server
        environment:
            WAIT_HOST: db:3306
        depends_on: 
            - db
    db:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: sakamichi_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password 
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
volumes:
    db-data:

